name: Bug Report
title: "[bug] "
description: Something went wrong? Submit a bug report and I'll check it out!
labels: ["bug"]
assignees:
  - nedoxff
body:
  - type: textarea
    id: cause
    attributes:
      label: When or how did the error occur?
  - type: textarea
    id: error
    attributes:
      label: Error
      description: This should be filled automatically if you pressed the "Create bug report" button.
  - type: dropdown
    id: browser
    attributes:
      label: Browser
      options:
        - Chromium-based (Chrome, Helium, Opera, etc.)
        - Firefox-based (Firefox, Zen, etc.)
        - Other
    